config/routes.rb
StockShop::Application.routes.draw do
  root 'pages#root'
  
  resources :stocks, :stock_values, :decisions
end

app/models/decision.rb
class Decision < ActiveRecord::Base
  belongs_to :stock_value
  belongs_to :item_value
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :item_values

end

app/models/item_value.rb
class ItemValue < ActiveRecord::Base
	belongs_to :item
end

app/models/stock.rb
class Stock < ActiveRecord::Base
	has_many :stock_values
end

app/models/stock_value.rb
class StockValue < ActiveRecord::Base
	belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  before_filter :set_decision, :only => %w{edit update show}

  def show
  end

  def new
    @decision = Decisions.new
  end

  def create
    if @decision.save
      redirect to @decision
    else
      redirect_to :root
    end
  end

  def update
    if @decision.update_attributes(decision_params)
      redirect_to @decision
    else
       redirect_to :root
    end
  end
  
  private

  def set_decision
    @decision = Decision.find(params[:id])
  end
  def decision_params
    params.require(:decision).permit(:stock_value, :item_value, :winner)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	include ApplicationHelper, ItemsHelper
  def root
    @stock = Stock.new
  end
end

app/controllers/stock_values_controller.rb
class StockValuesController < ApplicationController
  before_filter :set_stock_value, :only => %w{edit update show}

  
  def new
    @stock_value = StockValue.new
  end

  def show
  end


  private

  def set_stock_value
    @stock_value = StockValue.find(params[:id])
  end
  
  def stock_value_params
    params.require(:stock_value).permit(:value)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
	include StocksHelper, ApplicationHelper
	before_filter :set_stock, :only => %w{edit update show}

	def show
	end

	def new
		@stock = Stock.new
	end

	def create
		@symbol = stock_params[:stock_symbol].upcase
		@exchange = stock_params[:stock_exchange]


		# @stock = Stock.new(stock_params)
		# @stock.stock_symbol = @stock.stock_symbol.upcase

		@stock = Stock.find_or_create_by(stock_symbol: @symbol, stock_search: @exchange)
		@exchange = nil if @exchange.eql? "USA"
		stock_array = stock_details(@symbol, @exchange)
		@stock_value = StockValue.find_by(value: stock_array[2], created_at: today_range)
		@stock_value = StockValue.new({stock: @stock, value: stock_array[2]}) if @stock_value.nil?
		@stock.name = stock_array[0]
		@stock.stock_exchange = stock_array[1]
		Rails.logger.debug ">>>>>>#{@stock.inspect}"

		Rails.logger.debug ">>>>>>#{stock_array.inspect}"

		if @stock.save && @stock_value.save
			@decision = Decision.new
			@decision.stock_value = @stock_value
			@decision.item_value = product_under_price(@stock_value.value)
			redirect_to decision_url(@decision), notice: 'Stock was successfully created.' if @decision.save
		else
			redirect_to :root
		end
	end

	private
	def set_stock
    @stock = Stock.find(params[:id])
  end
	def stock_params
		params.require(:stock).permit(:stock_symbol, :stock_exchange, :name, :stock_search)
	end
end

app/helpers/application_helper.rb
require 'semantics3'

module ApplicationHelper
	def today_range
		(Date.today.beginning_of_day..Date.today.end_of_day)
	end
	
	def product_under_price(price)
		# @item_value = ItemValue.where("value <= ? AND item.img_url IS NOT NULL", price).order("value DESC").limit(1)
		@item_value = ItemValue.where("value <= ?", price).order("value DESC").limit(1) #unless !@item_value.nil?
		@item_value.first
	end
	
	def load_database(pages, le)
		load_products(pages, le)
	end
	
	private
  API_KEY = 'SEM3547B8A069D38345D3EA45A5705E41112'
  API_SECRET = 'MWNhODYxZTNiYjcwYTlhZmUwN2Q4MzY3NTJlYmY4NWU'
  
	def load_products(max = 5, le = 0)
  	@sem3 ||= Semantics3::Products.new(API_KEY, API_SECRET)
  	@sem3.clear
    @sem3.products_field("cat_id", 13658)
    @sem3.products_field("sitedetails", "latestoffers", "currency", "USD" )
    @sem3.products_field("sitedetails", "latestoffers", "price", le - 1) if le > 0
    @sem3.products_field("sort", "price", "asc")
		
		constructedJson = @sem3.get_query_json("products")
		Rails.logger.debug ">>>>>>>#{constructedJson}"
		productsHash = @sem3.get_products
		
		page = 0
		while (page < max)
			page = page + 1
			
			productsHash["results"].each do |product|
				next if product["sitedetails"].nil?
				product_name = product["name"]
				product_base_url = product["sitedetails"].first["name"]
				product_full_url = product["sitedetails"].first["url"]
				
				@item = Item.find_by(name: product_name)
				@item = Item.new({name: product_name, base_site: product_base_url, full_site: product_full_url}) if @item.nil?
				if !@item.save
					Rails.logger.debug "Error saving item object: #{@item.errors}"
				else
					product_price = product["price"]
					@item_value = ItemValue.find_by(value: product_price, created_at: today_range)
					@item_value = ItemValue.new({value: product_price, item: @item}) if @item_value.nil?
					
					if !@item_value.save
						Rails.logger.debug "Error saving item_value object #{@item_value.errors}"
					end
				end
			end
			
			productsHash = @sem3.iterate_products
		end
	end
end

app/helpers/items_helper.rb
require 'mechanize'

module ItemsHelper
  Regex = {
    "walmart.com" => /http:\/\/i.walmartimages.com\/i\/p\/.+/,
    "frys.com" => /http:\/\/images.frys.com\/art\/product\/.+/,
    "newegg.com" => /.+\/ProductImageCompressAll300\/.+/,
    "radioshack.com" => /.+\/graphics\/product_images\/.+/
  }
  
  def get_image(item)
    if !item.full_site.nil? && Regex.has_key?(item.base_site)
      begin
        page = agent.get(item.full_site)
        scrape_image_with_regex page, Regex[item.base_site]
      rescue
        Rails.logger.error "Something went horrible with requesting #{item.full_site}"
      end
    end
  end
  
  def scrape_image_with_regex(page, regex)
    page.images_with(src: regex).first.to_s
  end
  
  private
  def agent
    @agent ||= Mechanize.new
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stocks_helper.rb
require 'open-uri'
require 'csv'

module StocksHelper
	
	def stock_details(symbol, exchange)
		url = "http://finance.yahoo.com/d/quotes.csv?s=#{symbol}.#{exchange}&f=nxl1"
		csv = CSV.parse(open(url).read)
		result = Array.new
		csv.each do |row|
			result += row
		end
		result
	end
end

app/views/decisions/_item_tweet.html.haml
<div class="twits">
<a href="https://twitter.com/share" class="twitter-share-button" style="margin:0 auto;" data-url="http://stockshop.r13.railsrumble.com" data-text="I choose the item! Which will you pick?" data-count="none">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></div>

app/views/decisions/_stock_tweet.html.haml
<div class="twits">
<a href="https://twitter.com/share" class="twitter-share-button" style="margin:0 auto;" data-url="http://stockshop.r13.railsrumble.com" data-text="I choose the stock! Which will you pick?" data-count="none">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></div>

app/views/decisions/show.html.haml
.content.no-alpha
  - if @decision.winner == nil
    .item.pull-left.decision-size
      .top-bar
        %h3.text-center #{@decision.stock_value.stock.stock_symbol.upcase} - #{@decision.stock_value.stock.name}
        %h3.text-center  #{@decision.stock_value.stock.stock_exchange}
      .center-bar
      .bottom-bar
        %h3.text-center  Value: $#{number_with_precision(@decision.stock_value.value, :precision => 2)}
        .text-center
          = link_to 'Choose Stock', decision_path(:decision => {:winner => 1}), :method=> :put, :class => 'btn'
    .product.pull-right.decision-size
      .top-bar
        %h3.text-center #{truncate(@decision.item_value.item.name, :length => 38)}
      .center-bar{ :style => "background:url(#{@decision.item_value.item.img_url}) no-repeat center center;"}
      .bottom-bar
        %h3.text-center  Value: $#{number_with_precision(@decision.item_value.value, :precision => 2)}
        .text-center
          = link_to 'Choose Product', decision_path(:decision => {:winner => 2}), :method=> :put, :class => 'btn'
  - elsif @decision.winner == 1
    .item.center
      .top-bar
        %h3.text-center You chose #{@decision.stock_value.stock.stock_symbol.upcase} stock over #{@decision.item_value.item.name}!
      .center-bar
      .bottom-bar
        %h3.text-center  Value: $#{number_with_precision(@decision.stock_value.value, :precision => 2)}
        = render 'stock_tweet'
  - elsif @decision.winner == 2
    .product.center
      .top-bar
        %h3.text-center You chose #{@decision.item_value.item.name} over #{@decision.stock_value.stock.stock_symbol.upcase} stock!
      .center-bar{ :style => "background:url(#{@decision.item_value.item.img_url}) no-repeat center center;"}
      .bottom-bar
        %h3.text-center  Value: $#{number_with_precision(@decision.item_value.value, :precision => 2)}
        = render 'item_tweet'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Stock or Not
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  .alpha-div 
    .logo.pull-left= link_to image_tag( 'StockOrNot.png'), root_path
    .pull-right= link_to image_tag( 'vote.png'), 'http://railsrumble.com/entries/234-stockshop'
  %body
    = yield

app/views/pages/_form.html.haml
.content
  = form_for @stock do |f|
    %fieldset
      .form-inline.text-center
        = f.radio_button :stock_exchange, 'USA', :checked => true, :style => "margin-bottom:10px"
        = f.label :stock_exchange, 'USA', :value => 'USA'
        = f.radio_button :stock_exchange, 'TO', :style => "margin-bottom:10px"
        = f.label :stock_exchange, 'Toronto', :value => 'TO'
        = f.radio_button :stock_exchange, 'L', :style => "margin-bottom:10px"
        = f.label :stock_exchange, 'London', :value => 'L'
      %br
      .control-group.text-center
        = f.text_field :stock_symbol, :placeholder => "AAPL, BBRY, etc", :class => "stock_input"
        = f.submit "Search", :class => "btn"
      %p.text-center.blurb Search for your favourite (or least favourite) stock and find out what you can buy with it!
      

app/views/pages/root.html.haml
= render 'form'

app/views/stock_values/show.html.haml
%h3.text-center #{@stock_value.stock.stock_symbol}
%h3.text-center  Value: $#{@stock_value.value}

app/views/stocks/show.html.haml
%h3= @stock.stock_symbol
%h3= @stock_value